# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-TextForge
version:      0.01
version_from: lib/Catalyst/View/TextForge.pm
installdirs:  site
requires:
    Text::Forge:                   4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
